on:
  schedule:
    # 1:05 past midnight UTC
    - cron: "5 1 * * *"

name: "Sync with upstream"
jobs:
  patch:
    name: "Sync"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v3"
        with:
          submodules: true

      - name: "Setup toolchain"
        uses: "actions-rs/toolchain@v1"
        with:
          toolchain: "stable"
          profile: "minimal"
          override: true

      - uses: "Swatinem/rust-cache@v1"
        with:
          cache-on-failure: true

      - name: "Config Git"
        run: |
          git config user.name "Jonathan LEI"
          git config user.email "me@xjonathan.dev"

      - name: "Update main"
        run: |
          git fetch
          git remote add upstream https://github.com/eqlabs/pathfinder
          git fetch upstream
          git checkout main
          git reset --hard upstream/main
          git checkout origin/home ./README.md
          git checkout origin/home ./.github/
          git add .
          git commit -m "chore: README and CI changes"

      - name: "Update patch"
        run: |
          # First, point `patch` to local `main`
          git checkout patch
          git reset --hard main

          # Here, we pick commits on `patch` except the first one (which is the old `main` update).
          # We do this instead of a naive rebase on `main` because the commit made on `main` could
          # have changed in content.
          MERGE_BASE=$(git merge-base origin/patch upstream/main)
          COMMIT_COUNT=$(git rev-list $MERGE_BASE..origin/patch | wc -l)
          git cherry-pick origin/patch^$(($COMMIT_COUNT-1))..origin/patch

      - name: "Cargo build"
        run: |
          cargo build --all --all-targets

      - name: "Push branches"
        run: |
          git checkout main
          git push --force-with-lease
          git checkout patch
          git push --force-with-lease
